# Generated by Django 3.1.3 on 2021-01-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='notices',
            field=models.CharField(default='', max_length=50, verbose_name='备注'),
        ),
    ]
