# Generated by Django 3.1.3 on 2021-01-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_server_notices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='notices',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='备注'),
        ),
    ]
