# Generated by Django 3.1.3 on 2021-01-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(default='', max_length=64, verbose_name='路径'),
        ),
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.ManyToManyField(to='web.Server', verbose_name='关联服务器'),
        ),
    ]
