# Generated by Django 3.1.3 on 2021-01-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210107_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='path',
            field=models.CharField(default='', max_length=64, verbose_name='线上路径'),
        ),
        migrations.CreateModel(
            name='DeployTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, verbose_name='标识')),
                ('tag', models.CharField(max_length=32, verbose_name='版本')),
                ('status', models.SmallIntegerField(choices=[(1, '待发布'), (2, '发布中'), (3, '成功'), (4, '失败')], default=1, verbose_name='状态')),
                ('before_download_script', models.TextField(blank=True, null=True, verbose_name='下载前脚本')),
                ('after_download_script', models.TextField(blank=True, null=True, verbose_name='下载后脚本')),
                ('before_deploy_script', models.TextField(blank=True, null=True, verbose_name='发布前脚本')),
                ('after_deploy_script', models.TextField(blank=True, null=True, verbose_name='发布后脚本')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='项目环境')),
            ],
        ),
    ]
