# Generated by Django 3.1.3 on 2021-01-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_hooktemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hooktemplate',
            old_name='hook',
            new_name='hook_type',
        ),
    ]
