# Generated by Django 3.1.2 on 2021-01-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('lightgrey', '待发布'), ('green', '成功'), ('red', '失败')], default='lightgrey', max_length=16, verbose_name='状态'),
        ),
    ]
